# Generated by Django 5.2.3 on 2025-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_session_student_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='queen', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='queen', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='password',
            field=models.CharField(default='queen', max_length=128),
            preserve_default=False,
        ),
    ]
