# Generated by Django 5.2.3 on 2025-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_moodentry_therapist_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
